"""Konstanten für die RLP Wetter Integration."""
from datetime import timedelta
from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorEntityDescription,
    SensorStateClass,
)
from homeassistant.const import UnitOfTemperature, UnitOfSpeed, PERCENTAGE, UnitOfPrecipitationDepth

DOMAIN = "rlp_wetter"
PLATFORMS = ["sensor"]

# --- Konfiguration ---
CONF_STATION_ID = "station_id"
DEFAULT_SCAN_INTERVAL = timedelta(minutes=5) # Update-Intervall

# --- API ---
# Dein Cloudflare Worker Endpunkt
API_ENDPOINT = "https://api.heyfordy.de/rlp-wetter"
REQUEST_TIMEOUT = 15 # Sekunden

# --- Sensoren ---
SENSOR_TYPES: tuple[SensorEntityDescription, ...] = (
    SensorEntityDescription(
        key="temp_2m_C",
        name="Temperatur (2m)",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="temp_20cm_C",
        name="Temperatur (20cm)",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False, # Standardmäßig deaktiviert
    ),
    SensorEntityDescription(
        key="luftfeuchte_prozent",
        name="Luftfeuchtigkeit",
        native_unit_of_measurement=PERCENTAGE,
        device_class=SensorDeviceClass.HUMIDITY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="wind_ms",
        name="Windgeschwindigkeit",
        native_unit_of_measurement=UnitOfSpeed.METERS_PER_SECOND,
        device_class=SensorDeviceClass.WIND_SPEED,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:weather-windy",
    ),
    SensorEntityDescription(
        key="blattnaesse_prozent",
        name="Blattnässe",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:leaf",
        entity_registry_enabled_default=False, # Standardmäßig deaktiviert
    ),
    SensorEntityDescription(
        key="niederschlag_mm",
        name="Niederschlag",
        native_unit_of_measurement=UnitOfPrecipitationDepth.MILLIMETERS,
        device_class=SensorDeviceClass.PRECIPITATION,
        state_class=SensorStateClass.MEASUREMENT, # oder TOTAL_INCREASING, wenn es akkumuliert wäre
        icon="mdi:weather-pouring",
    ),
)

# --- Stationsliste (Auszug, Rest unten im Code-Block) ---
# Format: "Anzeigename im Dropdown": sid (als String oder Integer)
STATION_LIST = {
    "Abentheuer": 44,
    "Alsheim": 122,
    "Alzey": 801,
    "Andernach": 802,
    "Annweiler": 247,
    "Anschau": 246,
    "Appenheim": 137,
    "Avelsbach": 29,
    "Bacharach": 78,
    "Bad-Neuenahr Ahrweiler": 803,
    "Bad Bergzabern": 90,
    "Bad Bergzabern (DWD)": 804,
    "Bad Dürkheim": 95,
    "Bad Dürkheim (DWD)": 805,
    "Bad Kreuznach": 7,
    "Bad Kreuznach DLR": 198,
    "Bad Kreuznach Zentrum": 350,
    "Bad Kreuznach (DWD)": 806,
    "Bad Marienberg": 807,
    "Bad Neuenahr": 86,
    "Baden-Baden-Geroldsau": 808,
    "Baumholder": 46,
    "Bechtheim": 123,
    "Berghausen": 23,
    "Bernkastel-Kues": 118,
    "Beuren": 200,
    "Bingen-Gaulsheim": 101,
    "Blankenrath": 809,
    "Bodenheim": 74,
    "Börfink": 203,
    "Bonn-Roleber": 810,
    "Boppard": 79,
    "Brauneberg": 111,
    "Briedel": 124,
    "Bruchweiler": 38,
    "Büchel (Flugplatz)": 811,
    "Büchelberg": 59,
    "Bundenthal": 204,
    "Calmont": 119,
    "Dackenheim": 13,
    "Dannenfels": 308,
    "Dannstadt": 205,
    "Darmstadt": 812,
    "Daxweiler": 252,
    "Deidesheim-Niederkirchen": 133,
    "Deuselbach": 813,
    "Dienheim": 16,
    "Dienstweiler": 18,
    "Dillenburg": 814,
    "Dolgesheim": 80,
    "Drais-Finthen": 83,
    "Dreis-Brück": 21,
    "Dromersheim": 17,
    "Dümpelfeld": 253,
    "Dunzweiler": 365,
    "Edesheim": 61,
    "Eich": 31,
    "Einöllen": 201,
    "Eisenach": 167,
    "Eisenschmitt": 249,
    "Elkhausen": 45,
    "Ellern": 42,
    "Ellerstadt": 98,
    "Elmstein": 227,
    "Enkenbach": 40,
    "Entenpfuhl": 233,
    "Esch": 5,
    "Eußerthal": 215,
    "Fischbach": 53,
    "Flomborn": 121,
    "Frankelbach": 304,
    "Frankenthal- Eppstein": 147,
    "Frankenthal-Mörsch": 158,
    "Frankfurt/Main": 816,
    "Frankfurt/Main-Westend": 817,
    "Freimersheim": 160,
    "Freinsheim": 77,
    "Gau-Algesheim": 73,
    "Gauchsberg": 303,
    "Geisenheim": 818,
    "Gelsdorf": 164,
    "Gerolstein": 238,
    "Göcklingen Holzbrühl": 52,
    "Göllheim": 257,
    "Gondershausen": 10,
    "Grenzau": 6,
    "Grünstadt-Asselheim": 93,
    "Grünstadt-Sausenheim": 94,
    "Guldental": 155,
    "Gundheim": 76,
    "Guntersblum": 120,
    "Hachenburg": 235,
    "Härtlingen": 239,
    "Hahn": 819,
    "Hatzenport": 117,
    "Hausen": 49,
    "Heidenfahrt": 72,
    "Heimbach-Weis": 28,
    "Herdorf": 363,
    "Hermeskeil": 310,
    "Hersdorf": 56,
    "Herxheimweyher": 12,
    "Hilgenroth": 820,
    "Hochspeyer": 302,
    "Höheinöd": 209,
    "Höhr-Grenzhausen": 237,
    "Hofgut Serrig": 171,
    "Hohenleimbach": 315,
    "Holzbach": 306,
    "Homberg": 208,
    "Hornbach": 242,
    "Hortenkopf": 240,
    "Hümmerich": 821,
    "Hüttgeswasen": 210,
    "Idar-Oberstein": 822,
    "Ingelheim": 71,
    "Isert": 22,
    "Kaiserslautern": 351,
    "Kaiserslautern (DWD)": 823,
    "Kall-Sistig": 824,
    "Kaltenborn": 47,
    "Kanzem": 109,
    "Kelberg": 251,
    "Kell am See": 35,
    "Kettenheim": 9,
    "Kirchberg": 211,
    "Kirchheimbolanden": 254,
    "Kirchweiler": 232,
    "Kirf-Beuren": 212,
    "Klein-Altendorf": 104,
    "Kleiner Feldberg/Taunus": 825,
    "Kleinich": 213,
    "Kleinniedesheim": 11,
    "Klüsserath": 151,
    "Koblenz": 352,
    "Körperich": 135,
    "Konz": 139,
    "Kruft": 136,
    "Kümbdchen": 169,
    "Kusel": 214,
    "Laacher See": 244,
    "Lachen Speyerdorf": 153,
    "Landau-Nussdorf": 89,
    "Landau-Wollmesheim": 87,
    "Laumersheim": 150,
    "Leimersdorf-Nierendorf": 65,
    "Leisel": 360,
    "Leisel_Forsten": 311,
    "Leistadt - Kallstadt": 85,
    "Leiwen": 69,
    "Lennebergwald": 316,
    "Lennestadt-Theten": 826,
    "Leutesdorf": 149,
    "Liebenscheid": 207,
    "Limburgerhof": 157,
    "Lingerhahn": 216,
    "Löhnberg-Obershausen": 827,
    "Ludwigshafen-Mundenheim": 353,
    "Lustadt": 14,
    "Maikammer": 96,
    "Mainz-Lerchenberg (ZDF)": 828,
    "Mainz-Marienborn": 2,
    "Mainz-Mombach": 354,
    "Manderscheid-Sonnenhof": 829,
    "Mannheim": 830,
    "Maring-Noviand": 161,
    "Maroth": 243,
    "Martinshöhe": 24,
    "Mayen": 130,
    "Mayschoß": 116,
    "Meckenheim": 148,
    "Meddersheim": 39,
    "Mehlingen": 170,
    "Meisburg": 217,
    "Merzalben": 301,
    "Merzkirchen": 27,
    "Montabaur": 831,
    "Morlautern": 26,
    "Müden": 156,
    "Mühlacker": 832,
    "Mülheim-Kärlich": 66,
    "Münstermaifeld": 15,
    "Mutterstadt": 144,
    "Nassau": 218,
    "Nastätten": 833,
    "Neef": 108,
    "Nentershausen": 245,
    "Neuhäusel": 364,
    "Neuhäusel_Forsten": 314,
    "Neumühle": 67,
    "Neunkirchen-Seelscheid-Krawinkel": 834,
    "Neunkirchen-Wellesweiler": 835,
    "Neustadt": 1,
    "Neuwied": 355,
    "Neuwied-Torney": 159,
    "Nideggen-Schmidt": 836,
    "Nierstein": 106,
    "Nittel": 110,
    "Norheim": 81,
    "Nürburg-Barweiler": 837,
    "Obermoschel": 258,
    "Obernhof": 174,
    "Oberwesel": 154,
    "Oberzerf": 43,
    "Offenbach-Wetterpark": 838,
    "Offstein": 103,
    "Olmscheid": 48,
    "Olsdorf": 839,
    "Oppenheim": 8,
    "Oppenheim LA": 68,
    "Ormsheimer Hof": 146,
    "Perl-Nennig": 840,
    "Peterslahr": 223,
    "Pforzheim-Ispringen": 841,
    "Piesport": 84,
    "Pirmasens": 842,
    "Pirmasens_Innenstadt": 385,
    "Pölich": 132,
    "Polch": 220,
    "Pommern": 114,
    "Reichshof-Eckenhagen": 843,
    "Rheingönheim": 145,
    "Rheinstetten": 844,
    "Riol": 30,
    "Rockenhausen": 259,
    "Rommersheim": 3,
    "Runkel-Ennerich": 845,
    "Ruppertsberg": 142,
    "Ruppertsecken": 846,
    "Saarbrücken-Burbach": 847,
    "Saarbrücken-Ensheim": 848,
    "Saulheim": 163,
    "Schaafheim-Schlierbach": 849,
    "Schaidt": 305,
    "Schallodenbach": 221,
    "Schifferstadt": 4,
    "Schneifelforsthaus": 850,
    "Schwabenheim-Selztal": 128,
    "Schweigen-Rechtenbach": 91,
    "Schweighofen": 64,
    "Seesbach": 222,
    "Selters": 224,
    "Selzen": 70,
    "Siebeldingen": 88,
    "Siegen (Kläranlage)": 851,
    "Simmern-Wahlbach": 852,
    "Singhofen": 51,
    "Sinzig": 225,
    "Speicher": 50,
    "Speyer": 127,
    "Speyer Nord": 386,
    "Sprendlingen": 41,
    "Stein": 248,
    "Steinborn": 34,
    "Steinweiler": 99,
    "Strickscheid": 19,
    "Strohn": 226,
    "Tholey": 853,
    "Traben-Trarbach": 113,
    "Trebur": 36,
    "Trier": 357,
    "Trier-Irsch": 230,
    "Trier-Petrisberg": 854,
    "Trier-Zewen": 855,
    "Üxheim": 255,
    "Ulmen": 57,
    "Valwig": 125,
    "Virneburg": 256,
    "Wachenheim": 62,
    "Waghäusel-Kirrlach": 856,
    "Wahlbach": 25,
    "Waibstadt": 857,
    "Waldems-Reinborn": 858,
    "Wallertheim": 166,
    "Wallhausen": 165,
    "Wascheid": 362,
    "Wascheid_Forsten": 312,
    "Weierhof": 33,
    "Weilerswist-Lommersum": 859,
    "Weinbiet": 860,
    "Weisenheim": 82,
    "Weiskirchen/Saar": 861,
    "Wershofen": 250,
    "Wicker": 32,
    "Wiersdorf": 37,
    "Wiesbaden-Auringen": 862,
    "Wiesweiler": 107,
    "Winningen": 115,
    "Wittlich-Bergweiler": 20,
    "Wöllstein": 60,
    "Wörth": 359,
    "Wormeldingen": 129,
    "Worms": 358,
    "Worms-Leiselheim": 126,
    "Worms (DWD)": 863,
    "Zell": 134,
    "Zellertal": 105,
    "Zeltingen": 112,
    "Zornheim": 75,
    "Zweibrücken": 229,
}

